import type {Metadata} from 'next';
import {cookies} from 'next/headers';
import {Manrope} from 'next/font/google';
import {createServerComponentClient} from '@supabase/auth-helpers-nextjs';
import {Nav} from '@/components';
import './globals.css';
import {AuthProvider} from '@/context';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
  display: 'swap',
});

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// do not cache this layout
export const revalidate = 0;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient({cookies});

  const {
    data: {session},
  } = await supabase.auth.getSession();

  const accessToken = session?.access_token || null;

  return (
    <html lang="en">
      <body
        className={`bg-grey max-w-[1192px] mx-auto px-4 ${manrope.className}`}
      >
        {accessToken ? <Nav /> : null}
        <AuthProvider accessToken={accessToken}>{children}</AuthProvider>
      </body>
    </html>
  );
}

export {metadata};
