import type {Metadata} from 'next';
import {Manrope} from 'next/font/google';
import {Nav} from '@/components';
import './globals.css';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
  display: 'swap',
});

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`bg-grey max-w-[1192px] mx-auto px-4 ${manrope.className}`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}

export {metadata};
