import type {Metadata} from 'next';
import {Manrope} from 'next/font/google';
import Nav from '@/components/nav';
import './globals.css';
import {AuthProvider} from '@/context';
import {createServerClient} from '@/helpers/server-client';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
  display: 'swap',
});

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  const supabase = createServerClient();

  const {
    data: {session},
  } = await supabase.auth.getSession();

  const accessToken = session?.access_token || null;

  return (
    <html lang="en">
      <body
        className={`bg-grey max-w-[1192px] mx-auto px-4 ${manrope.className}`}
      >
        {accessToken ? <Nav /> : null}
        <AuthProvider accessToken={accessToken}>
          {children}
          {modal}
        </AuthProvider>
      </body>
    </html>
  );
}

export {metadata};
